services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    command: .venv/bin/uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
